title: NCI-QCIF Training Platform Guide
description: Setup instructions for accessing and using our training platform.
theme: jekyll-theme-minimal
baseurl: "/nci-training-setup"

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
